// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fhebwzydbrecxowwyakw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZWJ3enlkYnJlY3hvd3d5YWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDU3NDgsImV4cCI6MjA3MzkyMTc0OH0.QP3ETP8ueJr4Une0u6FtVlwl4aACH3GdvxV8nj2-0eI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});